#!/usr/bin/env node
/* eslint-disable @typescript-eslint/no-var-requires */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SHARED = path.join(ROOT, 'packages', 'shared');
const PACKAGES = ['trigger', 'employee', 'knowledge-base', 'rag', 'synthetic-qa'];

const FILES = [
	'credentials/AgentBrainsIntegrationApi.credentials.ts',
	'icons/agentBrainsIntegration.svg',
	'nodes/constants.ts',
];

function header(rel) {
	return [
		`// THIS FILE IS AUTO-GENERATED — DO NOT EDIT.`,
		`// Source of truth: packages/shared/${rel}`,
		`// Regenerated by scripts/sync-shared.js (runs on postinstall + prebuild).`,
		'',
		'',
	].join('\n');
}

for (const pkg of PACKAGES) {
	for (const rel of FILES) {
		const from = path.join(SHARED, rel);
		const to = path.join(ROOT, 'packages', pkg, rel);
		fs.mkdirSync(path.dirname(to), { recursive: true });
		if (rel.endsWith('.ts')) {
			const body = fs.readFileSync(from, 'utf8');
			fs.writeFileSync(to, header(rel) + body);
		} else {
			fs.copyFileSync(from, to);
		}
	}
}

console.log(`synced ${FILES.length} shared files to ${PACKAGES.length} packages`);
