#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SHARED = path.join(ROOT, 'packages', 'shared');
const PACKAGES = ['trigger', 'employee', 'knowledge-base', 'rag', 'synthetic-qa'];
const ROOT_NODE_DIRS = [
	['knowledge-base', 'KnowledgeBase'],
	['synthetic-qa', 'SyntheticQa'],
	['trigger', 'IntegrationTrigger'],
	['rag', 'RAG'],
	['employee', 'Employee'],
];

const FILES = [
	'credentials/AgentBrainsIntegrationApi.credentials.ts',
	'icons/agentBrainsIntegration.svg',
	'nodes/constants.ts',
];

function header(rel) {
	return [
		`// THIS FILE IS AUTO-GENERATED — DO NOT EDIT.`,
		`// Source of truth: packages/shared/${rel}`,
		`// Regenerated by scripts/sync-shared.js (runs on postinstall + prebuild).`,
		'',
		'',
	].join('\n');
}

function copyDirRecursive(from, to) {
	fs.mkdirSync(to, { recursive: true });
	for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
		const fromPath = path.join(from, entry.name);
		const toPath = path.join(to, entry.name);
		if (entry.isDirectory()) {
			copyDirRecursive(fromPath, toPath);
		} else {
			fs.copyFileSync(fromPath, toPath);
		}
	}
}

for (const pkg of PACKAGES) {
	for (const rel of FILES) {
		const from = path.join(SHARED, rel);
		const to = path.join(ROOT, 'packages', pkg, rel);
		fs.mkdirSync(path.dirname(to), { recursive: true });
		if (rel.endsWith('.ts')) {
			const body = fs.readFileSync(from, 'utf8');
			fs.writeFileSync(to, header(rel) + body);
		} else {
			fs.copyFileSync(from, to);
		}
	}
}

const rootCredentialsDir = path.join(ROOT, 'credentials');
fs.mkdirSync(rootCredentialsDir, { recursive: true });
fs.copyFileSync(
	path.join(SHARED, 'credentials', 'AgentBrainsIntegrationApi.credentials.ts'),
	path.join(rootCredentialsDir, 'AgentBrainsIntegrationApi.credentials.ts'),
);

const rootIconsDir = path.join(ROOT, 'icons');
fs.mkdirSync(rootIconsDir, { recursive: true });
fs.copyFileSync(
	path.join(SHARED, 'icons', 'agentBrainsIntegration.svg'),
	path.join(rootIconsDir, 'agentBrainsIntegration.svg'),
);

const rootNodesDir = path.join(ROOT, 'nodes');
fs.mkdirSync(rootNodesDir, { recursive: true });
fs.copyFileSync(path.join(SHARED, 'nodes', 'constants.ts'), path.join(rootNodesDir, 'constants.ts'));

for (const [pkg, dirName] of ROOT_NODE_DIRS) {
	const from = path.join(ROOT, 'packages', pkg, 'nodes', dirName);
	const to = path.join(rootNodesDir, dirName);
	fs.rmSync(to, { recursive: true, force: true });
	copyDirRecursive(from, to);
}

console.log(`synced ${FILES.length} shared files to ${PACKAGES.length} packages`);
