// THIS FILE IS AUTO-GENERATED — DO NOT EDIT.
// Source of truth: packages/shared/nodes/constants.ts
// Regenerated by scripts/sync-shared.js (runs on postinstall + prebuild).

declare const process: { env: Record<string, string | undefined> };
const TARGET_ENV = (process.env.TARGET_ENV as 'sandbox' | 'staging') || 'sandbox';

export const DOMAINS: Record<string, string> = {
	sandbox: 'dwm-sndbx-ai.com',
	staging: 'agent-brains.com',
};

// Build-time default domain (hardcoded by patch-env.js at release time)
export const DOMAIN = DOMAINS[TARGET_ENV] || DOMAINS.sandbox;

/**
 * Resolve the API domain at runtime.
 * Uses the `domain` field from the credential if set, otherwise falls back
 * to the build-time default DOMAIN.
 */
export function getDomain(credentials: Record<string, unknown>): string {
	const override = (credentials.domain as string | undefined)?.trim();
	return override || DOMAIN;
}

// Polling defaults
export const SYNTHETIC_QA_MAX_WAIT_SECONDS = 900; // 15 minutes
export const SYNTHETIC_QA_POLL_INTERVAL_SECONDS = 5; // 5 seconds

// Build-time static URL constants (used as fallbacks; prefer getDomain() at runtime)
export const ADMIN_PANEL_EXTERNAL_BASE = `https://admin-panel.${DOMAIN}`;
export const EXTERNAL_SYNTH_USERS_URL = `${ADMIN_PANEL_EXTERNAL_BASE}/api/external/synthetic-users`;
export const EXTERNAL_GENERATE_OBJECTIVES_URL = `${ADMIN_PANEL_EXTERNAL_BASE}/api/external/generate-objectives`;
export const EXTERNAL_TEST_RUNS_START_URL = `${ADMIN_PANEL_EXTERNAL_BASE}/api/external/test-runs-start`;
export const EXTERNAL_TEST_RUNS_LIST_URL = `${ADMIN_PANEL_EXTERNAL_BASE}/api/external/test-runs-list`;
